name: Deploy Docker App
on:
  push:
    branches:
      - main, develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 레포지토리 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Docker Hub 로그인
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3️⃣ Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/paytime:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/paytime:latest

      # 4️⃣ EC2 서버에 SSH로 접속하여 최신 컨테이너 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/paytime:latest
            docker stop paytime || true
            docker rm paytime || true
            docker run -d -p 80:3000 --name my-app ${{ secrets.DOCKER_USERNAME }}/paytime:latest
